name: Python Tests

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}/devcontainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Run test in dev container image
      uses: devcontainers/ci@v0.3
      with:
        cacheFrom: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
        push: never
        runCmd: |
          make install-all-packages
          make run-test
          make clean